HospitalsAPP/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :conversations
  #get 'chat/show'
  get 'chat/show', to: 'chat#show'
  get '/chat/new', to: 'chat#new'
  get 'conversations/:id/messages', to: 'conversations#messages'
  post '/chat/create', to: 'chat#create'

  resources :medical_cards do
    collection do
      get :past
    end
  end
  resources :medical_cards do
    patch :mark_attended, on: :member
    patch :mark_not_attended, on: :member
  end
  # devise_for :users
  resources :medical_records
  resources :patients do
    resources :medical_cards, only: [:index], controller: 'medical_cards'
  end

  resources :doctors
  resources :hospitals
  resources :records

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    match '/users/sign_out', to: 'devise/sessions#destroy', via: %i[get delete]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
end

HospitalsAPP/app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :patient, class_name: 'User'
  belongs_to :doctor, class_name: 'User'
  has_many :messages
end

HospitalsAPP/app/controllers/conversation_controller.rb
class ConversationController < ApplicationController
  def index
  end
  def show
    @curusr=current_user
    @conversations = current_user.conversations
    #render json: @conversations
  end

  def create
    @conversation = Conversation.find_by(doctor_id: params[:doctor_id], patient_id: params[:patient_id])
    if @conversation.nil?
      @conversation = Conversation.new(conversation_params)
    if @conversation.save
      redirect_to @conversation
    else
      render :new
    end
    else
      redirect_to @conversation
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:doctor_id, :patient_id)
  end
end

HospitalsAPP/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
  end
  def show
    @conversation = Conversation.find(params[:id])
    #render json: @conversations
  end
  def new
    @conversation = Conversation.new
  end

  def messages
    conversation = Conversation.find(params[:id])
    messages = conversation.messages
    render json: messages
  end
  def create
    @conversation = Conversation.find_by(doctor_id: params[:doctor_id], patient_id: params[:patient_id])
    if @conversation.nil?
      @conversation = Conversation.new(conversation_params)
      if @conversation.save
        redirect_to chat_show_url
      else
        #render :new
      end
    else
      redirect_to chat_show_url
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:doctor_id, :patient_id)
  end
end

HospitalsAPP/app/helpers/conversation_helper.rb
module ConversationHelper
end

HospitalsAPP/app/helpers/conversations_helper.rb
module ConversationsHelper
end

HospitalsAPP/app/views/conversations/_conversation.html.erb
<div id="<%= dom_id conversation %>">
</div>

HospitalsAPP/app/views/conversations/_form.html.erb
<%= form_with(model: conversation) do |form| %>
  <% if conversation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

HospitalsAPP/app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render "form", conversation: @conversation %>

<br>

<div>
  <%= link_to "Show this conversation", @conversation %> |
  <%= link_to "Back to conversations", conversations_path %>
</div>

HospitalsAPP/app/views/conversations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Conversations</h1>

<div id="conversations">
  <% @conversations.each do |conversation| %>
    <%= render conversation %>
    <p>
      <%= link_to "Show this conversation", conversation %>
    </p>
  <% end %>
</div>

<%= link_to "New conversation", new_conversation_path %>

HospitalsAPP/app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render "form", conversation: @conversation %>

<br>

<div>
  <%= link_to "Back to conversations", conversations_path %>
</div>

HospitalsAPP/app/views/conversations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @conversation %>

<div>
  <%= link_to "Edit this conversation", edit_conversation_path(@conversation) %> |
  <%= link_to "Back to conversations", conversations_path %>

  <%= button_to "Destroy this conversation", @conversation, method: :delete %>
</div>