HospitalsAPP/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :conversations
  #get 'chat/show'
  get 'chat/show', to: 'chat#show'
  get '/chat/new', to: 'chat#new'
  get 'conversations/:id/messages', to: 'conversations#messages'
  post '/chat/create', to: 'chat#create'

  resources :medical_cards do
    collection do
      get :past
    end
  end
  resources :medical_cards do
    patch :mark_attended, on: :member
    patch :mark_not_attended, on: :member
  end
  # devise_for :users
  resources :medical_records
  resources :patients do
    resources :medical_cards, only: [:index], controller: 'medical_cards'
  end

  resources :doctors
  resources :hospitals
  resources :records

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    match '/users/sign_out', to: 'devise/sessions#destroy', via: %i[get delete]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
end

HospitalsAPP/app/models/medical_card.rb
# frozen_string_literal: true

class MedicalCard < ApplicationRecord # rubocop:todo Style/Documentation
  belongs_to :patient
  # belongs_to :doctor
  belongs_to :hospital
  has_many :records
end

HospitalsAPP/app/controllers/medical_cards_controller.rb
# frozen_string_literal: true

class MedicalCardsController < ApplicationController # rubocop:todo Style/Documentation
  before_action :set_medical_card, only: %i[show edit update destroy]
  # before_action :ensure_doctor, only: [:new, :create]

  # GET /medical_cards or /medical_cards.json
  def index
    if params[:patient_id].present?
      @patient = Patient.find(params[:patient_id])
      @medical_cards = @patient.medical_cards.where('appointment_date >= ?', Time.now).order(appointment_date: :asc)
    else
      @medical_cards = MedicalCard.where('appointment_date >= ?', Time.now).order(appointment_date: :asc)
    end
    @past_medical_cards = MedicalCard.where('appointment_date < ?', Time.now).order(appointment_date: :desc)
  end

  def past
    @medical_cards = MedicalCard.where('appointment_date < ?', Time.now).order(appointment_date: :desc)
    render :index
  end

  # GET /medical_cards/1 or /medical_cards/1.json
  def show; end

  def mark_attended
    @medical_card = MedicalCard.find(params[:id])
    if @medical_card.update(attended: true)
      render json: { attended: true }
    else
      render json: { error: 'Failed to update attendance status' }, status: :unprocessable_entity
    end
  end

  def mark_not_attended
    @medical_card = MedicalCard.find(params[:id])
    if @medical_card.update(attended: false)
      render json: { attended: false }
    else
      render json: { error: 'Failed to update attendance status' }, status: :unprocessable_entity
    end
  end

  # GET /medical_cards/new
  def new
    @medical_card = MedicalCard.new
    @patients = Patient.all
    @doctors = Doctor.all
    @hospitals = Hospital.all
  end

  # GET /medical_cards/1/edit
  def edit; end

  # POST /medical_cards or /medical_cards.json
  def create
    @medical_card = MedicalCard.new(medical_card_params)

    respond_to do |format|
      if @medical_card.save
        format.html { redirect_to medical_card_url(@medical_card), notice: 'Medical card was successfully created.' }
        format.json { render :show, status: :created, location: @medical_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medical_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_cards/1 or /medical_cards/1.json
  def update
    respond_to do |format|
      if @medical_card.update(medical_card_params)
        format.html { redirect_to medical_card_url(@medical_card), notice: 'Medical card was successfully updated.' }
        format.json { render :show, status: :ok, location: @medical_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medical_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_cards/1 or /medical_cards/1.json
  def destroy
    @medical_card.destroy!

    respond_to do |format|
      format.html { redirect_to medical_cards_url, notice: 'Medical card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_medical_card
    @medical_card = MedicalCard.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def medical_card_params
    params.require(:medical_card).permit(:medical_card_id, :patient_id, :doctor_id, :hospital_id, :diagnosis,
                                         :appointment_date, :appointment_type)
  end

  def ensure_doctor
    return if current_user.doctor.present?

    flash[:alert] = 'Тільки доктори можуть створювати нові записи.'
    redirect_to root_path
  end
end

HospitalsAPP/app/helpers/medical_cards_helper.rb
# frozen_string_literal: true

module MedicalCardsHelper # rubocop:todo Style/Documentation
end

HospitalsAPP/app/views/medical_cards/_form.html.erb
<%= form_with(model: medical_card, local: true) do |form| %>
  <% if medical_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medical_card.errors.count, "error") %> prohibited this medical_card from being saved:</h2>

      <ul>
        <% medical_card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :medical_card_id %>
    <%= form.number_field :medical_card_id %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.collection_select :patient_id, Patient.all, :id, :pname, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.collection_select :doctor_id, Doctor.all, :id, :dname, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :hospital_id %>
    <%= form.collection_select :hospital_id, Hospital.all, :id, :name, prompt: true %>
  </div>

  <div class="field">
  <%= form.label :diagnosis %>
  <%= form.text_field :diagnosis %>
</div>

  <div class="field">
    <%= form.label :appointment_date %>
    <%= form.datetime_field :appointment_date, class: 'form-control', placeholder: 'YYYY-MM-DD HH:MM' %>
  </div>

  <div class="field">
    <%= form.label :appointment_type %>
    <%= form.select :appointment_type, ['Операція', 'Консультація'], prompt: 'Оберіть тип прийому' %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

HospitalsAPP/app/views/medical_cards/_medical_card.html.erb
<div id="<%= dom_id medical_card %>">
  <p>
    <strong>Medical card:</strong>
    <%= medical_card.medical_card_id %>
  </p>

  <p>
    <strong>Patient:</strong>
    <%= medical_card.patient_id %>
  </p>

  <p>
    <strong>Doctor:</strong>
    <%= medical_card.doctor_id %>
  </p>

  <p>
    <strong>Hospital:</strong>
    <%= medical_card.hospital_id %>
  </p>

  <!--<p>
    <strong>Diagnosis:</strong>
    <%= medical_card.diagnosis %>
  </p>-->

</div>

HospitalsAPP/app/views/medical_cards/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2 class="mb-0">Editing medical card</h2>
        </div>

        <% if current_user.patient? %>
          <%= form_for @medical_card do |form| %>
            <div class="form-group">
              <%= form.label :appointment_date, "Appointment Date" %>
              <%= form.datetime_field :appointment_date, class: 'form-control', value: @medical_card.appointment_date.strftime("%Y-%m-%d %H:%M") %>
            </div>

            <div class="actions">
              <%= form.submit "Save Changes", class: 'btn btn-primary' %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="mt-3">
        <%= link_to "Show this medical card", @medical_card, class: 'btn btn-secondary' %> |
        <%= link_to "Back to medical cards", medical_cards_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

HospitalsAPP/app/views/medical_cards/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card animate__animated animate__fadeIn">
        <div class="card-header text-center">
          <h2 class="mb-0">Future Appointments</h2>
        </div>
        <div class="card-body">
          <% if @medical_cards.any? %>
            <div class="row row-cols-1 gy-3">
              <% @medical_cards.each do |medical_card| %>
                <div class="col">
                  <div class="card mb-3 appointment-card animate__animated animate__fadeIn" data-card-id="<%= medical_card.id %>">
                    <div class="card-body">
                      <div class="medical-record-info animate__animated animate__fadeIn">
                        <h5 class="card-title">Medical Record ID: <%= medical_card.medical_card_id %></h5>
                        <p class="card-text">Appointment Type: <%= medical_card.appointment_type %></p>
                        <p class="card-text">Patient: <%= medical_card.patient.pname %></p>
                        <p class="card-text">Hospital: <%= medical_card.hospital.name %></p>
                      </div>
                      <% if current_user.doctor? %>
                        <p class="card-text">Appointment Date: <%= medical_card.appointment_date ? medical_card.appointment_date.strftime("%d/%m/%Y %H:%M") : 'Not set' %></p>
                        <div class="attendance-buttons">
                          <%= button_to 'Attended', mark_attended_medical_card_path(medical_card), method: :patch, class: 'btn btn-success', remote: true, data: { url: mark_attended_medical_card_path(medical_card) } %>
                          <%= button_to 'Not Attended', mark_not_attended_medical_card_path(medical_card), method: :patch, class: 'btn btn-danger', remote: true, data: { url: mark_not_attended_medical_card_path(medical_card) } %>
                        </div>
                        <% elsif current_user.patient? %>
                          <div class="patient-appointment">
                            <div class="alert alert-info appointment-info" role="alert">
                              <i class="far fa-calendar-alt appointment-icon"></i>
                              <div class="appointment-date">
                                <strong>Appointment Date:</strong><br>
                                <%= medical_card.appointment_date ? medical_card.appointment_date.strftime("%d/%m/%Y %H:%M") : 'Not set' %>
                              </div>
                            </div>
                            <%= link_to 'Edit appointement date', edit_medical_card_path(medical_card), class: 'btn btn-primary btn-sm animate__animated animate__fadeIn' %>
                          </div>
                        <% else %>
                          <%= link_to 'Show', medical_card, class: 'btn btn-primary btn-sm animate__animated animate__fadeIn' %>
                          <%= link_to 'Edit', edit_medical_card_path(medical_card), class: 'btn btn-primary btn-sm animate__animated animate__fadeIn' %>
                          <%= link_to 'Destroy', medical_card, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm animate__animated animate__fadeIn' %>
                        <% end %>
                        </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="alert alert-warning" role="alert">
              No future medical appointments available.
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card bg-light animate__animated animate__fadeIn">
        <div class="card-header text-center">
          <h2 class="mb-0">Past Appointments</h2>
        </div>
        <div class="card-body">
          <% if @past_medical_cards.any? %>
            <div class="row row-cols-1 gy-3">
              <% @past_medical_cards.each do |medical_card| %>
                <div class="col">
                  <div class="card mb-3 appointment-card animate__animated animate__fadeIn" data-card-id="<%= medical_card.id %>">
                    <div class="card-body">
                      <div class="medical-record-info animate__animated animate__fadeIn">
                        <h5 class="card-title">Medical Record ID: <%= medical_card.medical_card_id %></h5>
                        <p class="card-text">Appointment Type: <%= medical_card.appointment_type %></p>
                        <p class="card-text">Patient: <%= medical_card.patient.pname %></p>
                        <p class="card-text">Hospital: <%= medical_card.hospital.name %></p>
                      </div>
                      <% if current_user.doctor? %>
                        <p class="card-text">Appointment Date: <%= medical_card.appointment_date ? medical_card.appointment_date.strftime("%d/%m/%Y %H:%M") : 'Not set' %></p>
                        <div class="attendance-buttons">
                          <%= button_to 'Attended', mark_attended_medical_card_path(medical_card), method: :patch, class: 'btn btn-success', remote: true, data: { url: mark_attended_medical_card_path(medical_card) } %>
                          <%= button_to 'Not Attended', mark_not_attended_medical_card_path(medical_card), method: :patch, class: 'btn btn-danger', remote: true, data: { url: mark_not_attended_medical_card_path(medical_card) } %>
                        </div>
                        <% elsif current_user.patient? %>
                          <div class="patient-appointment">
                            <div class="alert alert-info appointment-info" role="alert">
                              <i class="far fa-calendar-alt appointment-icon"></i>
                              <div class="appointment-date">
                                <strong>Appointment Date:</strong><br>
                                <%= medical_card.appointment_date ? medical_card.appointment_date.strftime("%d/%m/%Y %H:%M") : 'Not set' %>
                              </div>
                            </div>
                            <%= link_to 'Edit appointement date', edit_medical_card_path(medical_card), class: 'btn btn-primary btn-sm animate__animated animate__fadeIn' %>
                          </div>
                        <% else %>
                          <%= link_to 'Show', medical_card, class: 'btn btn-primary btn-sm animate__animated animate__fadeIn' %>
                          <%= link_to 'Edit', edit_medical_card_path(medical_card), class: 'btn btn-primary btn-sm animate__animated animate__fadeIn' %>
                          <%= link_to 'Destroy', medical_card, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm animate__animated animate__fadeIn' %>
                        <% end %>

                        </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="alert alert-warning" role="alert">
              No past medical appointments available.
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

HospitalsAPP/app/views/medical_cards/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2 class="mb-0">New medical card</h2>
        </div>

        <div class="card-body">
          <%= render "form", medical_card: @medical_card %>
        </div>
      </div>

      <div class="mt-3">
        <%= link_to "Back to medical cards", medical_cards_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

HospitalsAPP/app/views/medical_cards/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header text-center bg-primary text-white">
          <h2 class="mb-0">Medical Record Details</h2>
        </div>

        <div class="card-body">
          <p class="mb-2">
            <strong>Medical Card ID:</strong>
            <%= @medical_card.medical_card_id %>
          </p>

          <p class="mb-2">
            <strong>Patient:</strong>
            <%= @medical_card.patient.pname %>
          </p>

          <p class="mb-2">
            <strong>Hospital:</strong>
            <%= @medical_card.hospital.name %>
          </p>
        </div>

        <div class="mt-3 text-center">
          <%= link_to 'Back', medical_cards_path, class: 'btn btn-secondary btn-lg' %>
        </div>
      </div>
    </div>
  </div>
</div>