HospitalsAPP/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :conversations
  #get 'chat/show'
  get 'chat/show', to: 'chat#show'
  get '/chat/new', to: 'chat#new'
  get 'conversations/:id/messages', to: 'conversations#messages'
  post '/chat/create', to: 'chat#create'

  resources :medical_cards do
    collection do
      get :past
    end
  end
  resources :medical_cards do
    patch :mark_attended, on: :member
    patch :mark_not_attended, on: :member
  end
  # devise_for :users
  resources :medical_records
  resources :patients do
    resources :medical_cards, only: [:index], controller: 'medical_cards'
  end

  resources :doctors
  resources :hospitals
  resources :records

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    match '/users/sign_out', to: 'devise/sessions#destroy', via: %i[get delete]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
end

HospitalsAPP/app/models/doctor.rb
# frozen_string_literal: true

class Doctor < ApplicationRecord # rubocop:todo Style/Documentation
  has_many :medical_cards
  has_many :records
  belongs_to :user, foreign_key: 'user_id'
  # has_many :patients
  belongs_to :hospital, foreign_key: 'hos_id', primary_key: 'rank' # ???
  # validation
  validates :dphone, format: { with: /\A?0\d{9}\z/,
                               message: 'must be a valid phone number' }

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "dname", "dock_id", "dphone", "hos_id", "id", "id_value", "spec", "updated_at", "user_id"]
  end
end

HospitalsAPP/app/controllers/doctors_controller.rb
# frozen_string_literal: true

class DoctorsController < ApplicationController # rubocop:todo Style/Documentation
  before_action :set_doctor, only: %i[show edit update destroy]

  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.includes(:hospital).all
  end

  # GET /doctors/1 or /doctors/1.json
  def show; end

  # GET /doctors/new
  def new
    @doctor = Doctor.new(user_id: params[:user_id])
  end

  # GET /doctors/1/edit
  def edit; end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)
    # @doctor.user_id = current_user.id
    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy!

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def doctor_params
    params.require(:doctor).permit(:dock_id, :dname, :spec, :dphone, :hos_id, :user_id)
  end
end

HospitalsAPP/app/helpers/doctors_helper.rb
# frozen_string_literal: true

module DoctorsHelper # rubocop:todo Style/Documentation
end

HospitalsAPP/app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>">
  <p>
    <strong>Dock:</strong>
    <%= doctor.dock_id %>
  </p>

  <p>
    <strong>Dname:</strong>
    <%= doctor.dname %>
  </p>

  <p>
    <strong>Spec:</strong>
    <%= doctor.spec %>
  </p>

  <p>
    <strong>Dphone:</strong>
    <%= doctor.dphone %>
  </p>

  <p>
    <strong>Hos:</strong>
    <%= doctor.hospital.name %>
  </p>

</div>

HospitalsAPP/app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :dock_id, style: "display: block" %>
    <%= form.number_field :dock_id %>
  </div>

  <div>
    <%= form.label :dname, style: "display: block" %>
    <%= form.text_field :dname %>
  </div>

  <div>
    <%= form.label :spec, style: "display: block" %>
    <%= form.text_field :spec %>
  </div>

  <div>
    <%= form.label :dphone, style: "display: block" %>
    <%= form.text_field :dphone, type: 'tel'%>
  </div>

  <div>
    <%= form.label :hos_id, style: "display: block" %>
    <%= form.collection_select :hos_id, Hospital.all, :rank, :name %>
  </div>

  <%= form.hidden_field :user_id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

HospitalsAPP/app/views/doctors/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2 class="mb-0">Editing doctor</h2>
        </div>

        <div class="card-body">
          <%= render "form", doctor: @doctor %>
        </div>
      </div>

      <div class="mt-3">
        <%= link_to "Show this doctor", @doctor, class: 'btn btn-primary' %> |
        <%= link_to "Back to doctors", doctors_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

HospitalsAPP/app/views/doctors/index.html.erb
<div class="card-header text-center">
  <h2 class="mb-0">Список лікарів</h2>
</div>

<div class="card-body">
  <%= link_to 'Створити нового лікаря', new_doctor_path, class: 'btn btn-primary mb-3' %>

  <% if @doctors.any? %>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>Рейтинговий номер (id)</th>
          <th>Ім'я</th>
          <th>Спеціальність</th>
          <th>Телефон</th>
          <th>Лікарня</th>
          <th colspan="5"></th>
        </tr>
        </thead>
        <tbody>
        <% @doctors.each do |doctor| %>
          <tr>
            <td><%= doctor.dock_id %></td>
            <td><%= doctor.dname %></td>
            <td><%= doctor.spec %></td>
            <td><%= doctor.dphone %></td>
            <td><%= doctor.hospital.name %></td>
            <td><%= link_to 'Інформація про лікарню', hospital_path(doctor.hospital), class: 'btn btn-info' %></td>
            <td><%= link_to 'Перегляд', doctor, class: 'btn btn-info' %></td>
            <td><%= link_to 'Редагувати', edit_doctor_path(doctor), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Видалити', doctor, method: :delete, data: { confirm: 'Ви впевнені?' }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="alert alert-warning" role="alert">
      Немає жодного лікаря.
    </div>
  <% end %>
</div>

HospitalsAPP/app/views/doctors/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2 class="mb-0">New doctor</h2>
        </div>

        <div class="card-body">
          <%= render "form", doctor: @doctor %>
        </div>
      </div>

      <div class="mt-3">
        <%= link_to "Back to doctors", doctors_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

HospitalsAPP/app/views/doctors/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card"> 
        <div class="card-header text-center"> 
          <h2 class="mb-0">Інформація про лікарів</h2>
        </div>

        <%= render @doctor %>

        <div class="mt-3">
          <%= link_to "Edit this doctor", edit_doctor_path(@doctor), class: 'btn btn-primary' %> |
          <%= link_to "Back to doctors", doctors_path, class: 'btn btn-secondary' %>

          <%= button_to "Destroy this doctor", @doctor, method: :delete, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  </div>
</div>